In [ ]:
import time, json
import pandas as pd
from datetime import datetime
from pathlib import Path
from utils import Helper

utils = Helper()
json_dir = Path(r"gstn_json")
final_content = []
for file_path in json_dir.glob("*.json"):
    print(str(file_path))
    data = utils.load_json(str(file_path))
    status = data.get("filingStatus",[])
    for items in status:
        for item in items:
            item["PAN_NO"] = file_path.stem
    
        final_content.extend(items)

pd.DataFrame(final_content).to_excel("PAN_DATA.xlsx", index=False)

In [1]:
import undetected_chromedriver as uc
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
import time
import pandas as pd
from datetime import datetime

cpath = r"C:\Users\kaustubh.keny\Downloads\Updated Company List (Listed  Unlisted)_Latest CFD.xlsx"
df = pd.read_excel(cpath, sheet_name = "All")
df.head(5)

,Status,Workstation Name,New cogencis Name (The & Ltd.),ISIN No,Company ID,PAN No
0,Listed,Infosys Ltd,Infosys Ltd.,INE009A01021,3486,AAACI4798L
1,Listed,GM Breweries Ltd,GM Breweries Ltd.,INE075D01018,2765,AAACG1653N
2,Listed,Havells India Ltd,Havells India Ltd.,INE176B01034,3060,AAACH0351E
3,Listed,Vimta Labs Ltd,Vimta Labs Ltd.,INE579C01029,8213,AAACV7244E
4,Listed,Swarna Securities Ltd,Swarna Securities Ltd.,INE595G01018,7452,AADCS1718H

In [8]:
df.columns

Index(['Status', 'Workstation Name', 'New cogencis Name (The & Ltd.)',
       'ISIN No', 'Company ID', 'GST No'],
      dtype='object')

In [7]:
companies = df[["Workstation Name","PAN No","Status"]]
condition1 = companies["PAN No"].apply(lambda x: len(str(x))>2)

df = companies[condition1]

print(len(df))


df.head(10)

7494

                          Workstation Name      PAN No  Status
0                              Infosys Ltd  AAACI4798L  Listed
1                         GM Breweries Ltd  AAACG1653N  Listed
2                        Havells India Ltd  AAACH0351E  Listed
3                           Vimta Labs Ltd  AAACV7244E  Listed
4                    Swarna Securities Ltd  AADCS1718H  Listed
5                        Kretto Syscon Ltd  AAACI4341M  Listed
6      Tata Teleservices (Maharashtra) Ltd  AAACH1458C  Listed
7            Tata Consultancy Services Ltd  AAACR4849R  Listed
8  Transformers and Rectifiers (India) Ltd  AACCT8243P  Listed
9                          L&T Finance Ltd  AACCA1963B  Listed

In [8]:
import pandas as pd

# Assuming df is your DataFrame
listed_df = df[df['Status'].str.lower() == 'listed']
unlisted_df = df[df['Status'].str.lower() == 'unlisted']

listed_df.to_json('listed.json', orient='records', indent=4)
unlisted_df.to_json('unlisted.json', orient='records', indent=4)

print("JSON files created successfully.")

JSON files created successfully.

In [10]:
# driver = uc.Chrome(version_main=145)
driver = webdriver.Chrome()
wait = WebDriverWait(driver, 20)

BASE_URL = "https://www.knowyourgst.com/gst-number-search/by-name-pan/"

driver.get(BASE_URL)
results = []
for idx, company in enumerate(companies[:]):
    # Find the input field by id
    
    input_box = driver.find_element(By.ID, "gstnumber")
    input_box.clear()
    input_box.send_keys(company)

    submit_btn = driver.find_element(By.CSS_SELECTOR, "input[type='submit']")
    submit_btn.click()
    
    time.sleep(1)
    boxes = driver.find_elements(By.CSS_SELECTOR, "div#searchresult")
    print(f"{idx + 1} RUNNING FOR: {company} Total: {len(boxes)}")
    
    if not boxes:
        results.append({
            "Query":company,
            "Company": "",
            "State": "",
            "GSTIN": "",
            "Link": ""
        })
    
    for box in boxes:

        link = box.find_element(By.TAG_NAME, "a").get_attribute("href")
        company_name = box.find_element(By.TAG_NAME, "h5").text.strip()
        strongs = box.find_elements(By.CSS_SELECTOR, "span.black-text strong")
        state = strongs[0].text.strip() if len(strongs) > 0 else ""
        gst_number = strongs[1].text.strip() if len(strongs) > 1 else ""

        results.append({
            "Query":company,
            "Company": company_name,
            "State": state,
            "GSTIN": gst_number,
            "Link": link
        })

driver.quit()

csv_name = f"gst_results_{datetime.now().strftime("%H%M%S")}.csv"

df = pd.DataFrame(results)
df.to_csv(csv_name, index=False)
print(f"[SAVED] {csv_name}")

#1618 run

1 RUNNING FOR: Blue Yonder India Pvt Ltd Total: 0
2 RUNNING FOR: Paragon Polymer Products Pvt Ltd Total: 3
3 RUNNING FOR: Emerson Electric Company (India) Pvt Ltd Total: 2
4 RUNNING FOR: Tamil Nadu State Transport Corporation Coimbatore Ltd Total: 1
5 RUNNING FOR: Dhanraj Solvex Pvt Ltd Total: 0
6 RUNNING FOR: Voltbek Home Appliances Pvt Ltd Total: 0
7 RUNNING FOR: Kanti Bijlee Utpadan Nigam Ltd Total: 0
8 RUNNING FOR: Gimatex Industries Pvt Ltd Total: 2
9 RUNNING FOR: Citiustech Healthcare Technology Pvt Ltd Total: 0
10 RUNNING FOR: Roma Builders Pvt Ltd Total: 1
11 RUNNING FOR: Daeseong India Automotive Pvt Ltd Total: 0
12 RUNNING FOR: Cmr-Toyotsu Aluminium India Pvt Ltd Total: 0
13 RUNNING FOR: Roche Diagnostics India Pvt Ltd Total: 2
14 RUNNING FOR: V-Trans India Ltd Total: 0
15 RUNNING FOR: Kellogg India Pvt Ltd Total: 9
16 RUNNING FOR: Emerson Process Management (India) Pvt Ltd Total: 9
17 RUNNING FOR: Milacron India Pvt Ltd Total: 0
18 RUNNING FOR: Sandhya Marines Ltd Total: 0
19 RUNNING FOR: Nec Corporation India Pvt Ltd Total: 0
20 RUNNING FOR: Saj Food Products Pvt Ltd Total: 10
21 RUNNING FOR: Creamline Dairy Products Ltd Total: 3
22 RUNNING FOR: Marvell India Pvt Ltd Total: 5
23 RUNNING FOR: Indian Synthetic Rubber Pvt Ltd Total: 1
24 RUNNING FOR: Alf Engineering Pvt Ltd Total: 8
25 RUNNING FOR: Indu Corporation Pvt Ltd Total: 18
26 RUNNING FOR: Vicky Jewellery Works Pvt Ltd Total: 1
27 RUNNING FOR: Chettinad Logistics Pvt Ltd Total: 1
28 RUNNING FOR: Iljin Automotive Pvt Ltd Total: 1
29 RUNNING FOR: Ankit Gems Pvt Ltd Total: 1
30 RUNNING FOR: Punjab State Transmission Corporation Ltd Total: 1
31 RUNNING FOR: Rucha Engineers Pvt Ltd Total: 2
32 RUNNING FOR: Jindal Coke Ltd Total: 0
33 RUNNING FOR: Keimed Pvt Ltd Total: 1
34 RUNNING FOR: Prodair Air Products India Pvt Ltd Total: 0
35 RUNNING FOR: Sudhakar Pvc Products Pvt Ltd Total: 0
36 RUNNING FOR: Abci Infrastructures Pvt Ltd Total: 7
37 RUNNING FOR: Joinmay Mumbai Electronics Pvt Ltd Total: 1
38 RUNNING FOR: Varsity Education Management Pvt Ltd Total: 0
39 RUNNING FOR: Corteva Agriscience India Pvt Ltd Total: 0
40 RUNNING FOR: Malabar Gold Palace Pvt Ltd Total: 0
41 RUNNING FOR: Ctrl S Datacenters Ltd Total: 1
42 RUNNING FOR: Bhagyalaxmi Rolling Mill Pvt Ltd Total: 0
43 RUNNING FOR: Chaitanya India Fin Credit Pvt Ltd Total: 0
44 RUNNING FOR: Sigma Aldrich Chemicals Pvt Ltd Total: 2
45 RUNNING FOR: Metarolls Ispat Pvt Ltd Total: 0
46 RUNNING FOR: Sigma Electric Manufacturing Corporation Pvt Ltd Total: 0
47 RUNNING FOR: Delhi Transco Ltd Total: 5
48 RUNNING FOR: Sanvira Industries Ltd Total: 0
49 RUNNING FOR: Goldi Sun Pvt Ltd Total: 0
50 RUNNING FOR: Arvindbhai Bechardas Jewellers Pvt Ltd Total: 0
51 RUNNING FOR: Veritas Finance Ltd Total: 1
52 RUNNING FOR: Danblock Brakes India Pvt Ltd Total: 1
53 RUNNING FOR: Ongc Tripura Power Company Ltd Total: 1
54 RUNNING FOR: Pioneer Aluminium Industries Ltd Total: 0
55 RUNNING FOR: Euronet Services India Pvt Ltd Total: 4
56 RUNNING FOR: Amrut Distilleries Pvt Ltd Total: 1
57 RUNNING FOR: Brembo Brake India Pvt Ltd Total: 1
58 RUNNING FOR: Lapp India Pvt Ltd Total: 10
59 RUNNING FOR: India Optel Ltd Total: 0
60 RUNNING FOR: Dlf Assets Ltd Total: 1
61 RUNNING FOR: Colorcon Asia Pvt Ltd Total: 5
62 RUNNING FOR: Uni-Com India Pvt Ltd Total: 4
63 RUNNING FOR: Devashree Ispat Pvt Ltd Total: 0
64 RUNNING FOR: Marks And Spencer Reliance India Pvt Ltd Total: 9
65 RUNNING FOR: Goyal Vegoils Ltd Total: 0
66 RUNNING FOR: Klj Polymers & Chemicals Ltd Total: 8
67 RUNNING FOR: Barmer Lignite Mining Company Ltd Total: 0
68 RUNNING FOR: Micro Units Development And Refinance Agency Ltd Total: 0
69 RUNNING FOR: Aarti Steels Ltd Total: 1
70 RUNNING FOR: Shree Ambika Sugars Ltd Total: 0
71 RUNNING FOR: Swarna Shilpi Jewellers (Chennai) Pvt Ltd Total: 0
72 RUNNING FOR: Credit Suisse Services (India) Pvt Ltd Total: 1
73 RUNNING FOR: Wapcos Ltd Total: 2
74 RUNNING FOR: Lubrizol Advanced Materials India Pvt Ltd Total: 1
75 RUNNING FOR: Nirmal Wires Pvt Ltd Total: 0
76 RUNNING FOR: Cnb Finwiz Pvt Ltd Total: 0
77 RUNNING FOR: Agilent Technologies India Pvt Ltd Total: 14
78 RUNNING FOR: Farmgate Agro Milch Pvt Ltd Total: 2
79 RUNNING FOR: Asvini Fisheries Pvt Ltd Total: 0
80 RUNNING FOR: Toyota Financial Services India Ltd Total: 0
81 RUNNING FOR: Dalmia Cement (North East) Ltd Total: 0
82 RUNNING FOR: Galaxy Automobiles Pvt Ltd Total: 2
83 RUNNING FOR: Red Hat India Pvt Ltd Total: 1
84 RUNNING FOR: Fosroc Chemicals (India) Pvt Ltd Total: 0
85 RUNNING FOR: Hindustan Colas Pvt Ltd Total: 15
86 RUNNING FOR: Inland World Logistics Pvt Ltd Total: 1
87 RUNNING FOR: P.L.R. Projects Pvt Ltd Total: 1
88 RUNNING FOR: Cargo Motors Pvt Ltd Total: 8
89 RUNNING FOR: Minera Steel & Power Pvt Ltd Total: 1
90 RUNNING FOR: Sunraja Oil Industries Pvt Ltd Total: 0
91 RUNNING FOR: Owens-Corning (India) Pvt Ltd Total: 0
92 RUNNING FOR: Rane Nsk Steering Systems Pvt Ltd Total: 1
93 RUNNING FOR: Kotak Mahindra Investments Ltd Total: 1
94 RUNNING FOR: Mandovi Motors Pvt Ltd Total: 1
95 RUNNING FOR: Ideal Fiscal Services Ltd Total: 0
96 RUNNING FOR: Kotak Mahindra Asset Management Company Ltd Total: 1
97 RUNNING FOR: Silox India Pvt Ltd Total: 0
98 RUNNING FOR: Sharekhan Ltd Total: 2
99 RUNNING FOR: Bsr Infratech India Ltd Total: 0
100 RUNNING FOR: Sms Ltd Total: 40
101 RUNNING FOR: Cargill Business Services India Pvt Ltd Total: 1
102 RUNNING FOR: Fuji Electric India Pvt Ltd Total: 0
103 RUNNING FOR: Skylark Feeds Pvt Ltd Total: 6
104 RUNNING FOR: Vimal Intertrade Pvt Ltd Total: 4
105 RUNNING FOR: Jakson Green Ltd Total: 0
106 RUNNING FOR: Atos Global It Solutions And Services Pvt Ltd Total: 0
107 RUNNING FOR: Mehta Gold Pvt Ltd Total: 0
108 RUNNING FOR: Kejriwal Geotech Pvt Ltd Total: 1
109 RUNNING FOR: B.S. Sponge Pvt Ltd Total: 1
110 RUNNING FOR: A1 Agri Global Ltd Total: 0
111 RUNNING FOR: Telangana Grameena Bank Total: 5
112 RUNNING FOR: Madhu Silica Pvt Ltd Total: 3
113 RUNNING FOR: Nivea India Pvt Ltd Total: 3
114 RUNNING FOR: Smc Infrastructures Pvt Ltd Total: 8
115 RUNNING FOR: Indev Infra Pvt Ltd Total: 0
116 RUNNING FOR: Google India Digital Services Pvt Ltd Total: 0
117 RUNNING FOR: Ds Spiceco Pvt Ltd Total: 1
118 RUNNING FOR: Fmi Automotive Components Pvt Ltd Total: 1
119 RUNNING FOR: Rajasthan Medical Services Corporation Ltd Total: 0
120 RUNNING FOR: Krishi Rasayan Exports Pvt Ltd Total: 9
121 RUNNING FOR: Toppan Speciality Films Pvt Ltd Total: 0
122 RUNNING FOR: Tk Elevator India Pvt Ltd Total: 0
123 RUNNING FOR: Max Infra (I) Pvt Ltd Total: 5
124 RUNNING FOR: Universal Corporation Ltd Total: 12
125 RUNNING FOR: Sultania Trade Pvt Ltd Total: 0
126 RUNNING FOR: Virchow Petrochemicals Pvt Ltd Total: 0
127 RUNNING FOR: Shubham Goldiee Masale Pvt Ltd Total: 1
128 RUNNING FOR: Nuvama Wealth And Investment Ltd Total: 0
129 RUNNING FOR: Gati Express And Supply Chain Pvt Ltd Total: 0
130 RUNNING FOR: Tricon Energy India Pvt Ltd Total: 1
131 RUNNING FOR: Wellness Forever Medicare Ltd Total: 1
132 RUNNING FOR: Nature Delight Dairy And Dairy Products Pvt Ltd Total: 0
133 RUNNING FOR: Netcracker Technology Solutions (India) Pvt Ltd Total: 0
134 RUNNING FOR: Indira Ivf Hospital Ltd Total: 1
135 RUNNING FOR: Ups Express Pvt Ltd Total: 0
136 RUNNING FOR: Apache Footwear India Pvt Ltd Total: 1
137 RUNNING FOR: Somani Ispat Pvt Ltd Total: 2
138 RUNNING FOR: J.K. Fenner (India) Ltd Total: 4
139 RUNNING FOR: Ranjit Buildcon Ltd Total: 2
140 RUNNING FOR: Sampoorna Feeds Pvt Ltd Total: 1
141 RUNNING FOR: Tmeic Industrial Systems India Pvt Ltd Total: 1
142 RUNNING FOR: Iss Facility Services India Pvt Ltd Total: 5
143 RUNNING FOR: Maa Kudargarhi Steels Pvt Ltd Total: 0
144 RUNNING FOR: Hindustan Shipyard Ltd Total: 3
145 RUNNING FOR: Isc Projects Pvt Ltd Total: 1
146 RUNNING FOR: Mspl Ltd Total: 0
147 RUNNING FOR: Kirti Dal Mills Ltd Total: 1
148 RUNNING FOR: Super Auto Forge Pvt Ltd Total: 1
149 RUNNING FOR: Eaton Power Quality Pvt Ltd Total: 5
150 RUNNING FOR: Rajapushpa Properties Pvt Ltd Total: 0
151 RUNNING FOR: Fanuc India Pvt Ltd Total: 4
152 RUNNING FOR: Pataka Industries Pvt Ltd Total: 1
153 RUNNING FOR: Sbi Payment Services Pvt Ltd Total: 11
154 RUNNING FOR: Bluecraft Agro Pvt Ltd Total: 0
155 RUNNING FOR: Dimexon Diamonds Ltd Total: 0
156 RUNNING FOR: Aragen Life Sciences Ltd Total: 0
157 RUNNING FOR: P. C. Patel Infra Pvt Ltd Total: 0
158 RUNNING FOR: Indian Immunologicals Ltd Total: 12
159 RUNNING FOR: Autocomp Corporation Panse Pvt Ltd Total: 0
160 RUNNING FOR: Smartgen Infra Pvt Ltd Total: 0
161 RUNNING FOR: Same Deutz-Fahr India Pvt Ltd Total: 2
162 RUNNING FOR: Sonkamal Enterprises Pvt Ltd Total: 2
163 RUNNING FOR: Bangiya Gramin Vikash Bank Total: 2
164 RUNNING FOR: Sri Jayalakshmi Automotives Pvt Ltd Total: 2
165 RUNNING FOR: Pg Technoplast Pvt Ltd Total: 0
166 RUNNING FOR: Manyata Promoters Pvt Ltd Total: 0
167 RUNNING FOR: Paayas Milk Producer Company Ltd Total: 0
168 RUNNING FOR: Nandan Terry Ltd Total: 0
169 RUNNING FOR: Mahindra Heavy Engines Ltd Total: 0
170 RUNNING FOR: Fis Global Business Solutions India Pvt Ltd Total: 2
171 RUNNING FOR: Premier Cables And Conductors Pvt Ltd Total: 0
172 RUNNING FOR: Cabcon India Ltd Total: 2
173 RUNNING FOR: Zebronics India Pvt Ltd Total: 9
174 RUNNING FOR: Mantena Infrasol Pvt Ltd Total: 0
175 RUNNING FOR: Tbea Energy (India) Pvt Ltd Total: 4
176 RUNNING FOR: Engineering Projects (India) Ltd Total: 38
177 RUNNING FOR: Rohan Motors Ltd Total: 4
178 RUNNING FOR: Beckman Coulter India Pvt Ltd Total: 1
179 RUNNING FOR: Sunbridge Agro Pvt Ltd Total: 0
180 RUNNING FOR: Sai Sulphonates Pvt Ltd Total: 0
181 RUNNING FOR: Seven Islands Shipping Ltd Total: 0
182 RUNNING FOR: Akamai Technologies India Pvt Ltd Total: 4
183 RUNNING FOR: Eco Protection Engineers Pvt Ltd Total: 5
184 RUNNING FOR: Jefferies India Pvt Ltd Total: 0
185 RUNNING FOR: Dana India Pvt Ltd Total: 2
186 RUNNING FOR: Humboldt Wedag India Pvt Ltd Total: 6
187 RUNNING FOR: Eternis Fine Chemicals Ltd Total: 0
188 RUNNING FOR: Aparna Enterprises Ltd Total: 0
189 RUNNING FOR: Vj Jindal Cocoa Pvt Ltd Total: 0
190 RUNNING FOR: Wanhua International (India) Pvt Ltd Total: 0
191 RUNNING FOR: Santhoshimathaa Edible Oils Refinery Pvt Ltd Total: 1
192 RUNNING FOR: Deesan Agro-Tech Pvt Ltd Total: 0
193 RUNNING FOR: Beam Global Spirits & Wine (India) Pvt Ltd Total: 4
194 RUNNING FOR: Bharat Serums And Vaccines Ltd Total: 9
195 RUNNING FOR: Toyota Boshoku Automotive India Pvt Ltd Total: 0
196 RUNNING FOR: Shreeyam Power And Steel Industries Ltd Total: 1
197 RUNNING FOR: Anmol Industries Ltd Total: 3
198 RUNNING FOR: Tayal Sons Pvt Ltd Total: 1
199 RUNNING FOR: Great Eastern Hire Purchase Pvt Ltd Total: 0
200 RUNNING FOR: Convergys India Services Pvt Ltd Total: 2
201 RUNNING FOR: Ankur Udyog Ltd Total: 3
202 RUNNING FOR: Tropical Agro System (India) Pvt Ltd Total: 3
203 RUNNING FOR: Al-Hamd Agro Food Products Pvt Ltd Total: 2
204 RUNNING FOR: Vidres India Ceramics Pvt Ltd Total: 1
205 RUNNING FOR: Anand Jewels (Indore) Pvt Ltd Total: 0
206 RUNNING FOR: Delhi State Civil Supplies Corpn Ltd Total: 0
207 RUNNING FOR: La Renon Healthcare Pvt Ltd Total: 0
208 RUNNING FOR: Tulsi Dyechem Pvt Ltd Total: 0
209 RUNNING FOR: Rana Motors Pvt Ltd. Total: 3
210 RUNNING FOR: Ims Health Analytics Services Pvt Ltd Total: 0
211 RUNNING FOR: Asian Institute Of Gastroenterology Pvt Ltd Total: 0
212 RUNNING FOR: Triumph Auto (Cv) Pvt Ltd Total: 0
213 RUNNING FOR: Solvay Specialities India Pvt Ltd Total: 0
214 RUNNING FOR: Sml Films Ltd Total: 0
215 RUNNING FOR: Connaught Plaza Restaurants Pvt Ltd Total: 9
216 RUNNING FOR: Sanghvi Foods Pvt Ltd Total: 0
217 RUNNING FOR: Sahyadri Farms Post Harvest Care Ltd Total: 0
218 RUNNING FOR: Shanghvi Finance Pvt Ltd Total: 0
219 RUNNING FOR: Grew Energy Pvt Ltd Total: 0
220 RUNNING FOR: Fena Pvt Ltd Total: 7
221 RUNNING FOR: Nutricia International Pvt Ltd Total: 14
222 RUNNING FOR: Daebu Automotive Seat India Pvt Ltd Total: 1
223 RUNNING FOR: Nexg Devices Pvt Ltd Total: 9
224 RUNNING FOR: Jalan Company Pvt Ltd Total: 0
225 RUNNING FOR: Anil Industries Katni Pvt Ltd Total: 0
226 RUNNING FOR: Ge Oil & Gas India Pvt Ltd Total: 0
227 RUNNING FOR: Hettich India Pvt Ltd Total: 2
228 RUNNING FOR: Raigarh Energy Generation Ltd Total: 0
229 RUNNING FOR: Khandelwal Edible Oils Pvt Ltd Total: 0
230 RUNNING FOR: Jbm Electric Vehicles Pvt Ltd Total: 0
231 RUNNING FOR: Dhanuka Soya Pvt Ltd Total: 1
232 RUNNING FOR: Odisha Gramya Bank Total: 2
233 RUNNING FOR: Gia India Laboratory Pvt Ltd Total: 0
234 RUNNING FOR: Raghava Constructions (India) Pvt Ltd Total: 5
235 RUNNING FOR: Ambashakti Industries Ltd Total: 1
236 RUNNING FOR: Amcor Flexibles India Pvt Ltd Total: 1
237 RUNNING FOR: Shah Virchand Govanji Jewellers Pvt Ltd Total: 1
238 RUNNING FOR: Manappuram Jewellers Ltd Total: 1
239 RUNNING FOR: Sam India Builtwell Pvt Ltd Total: 2
240 RUNNING FOR: Mandke Foundation Total: 3
241 RUNNING FOR: J. P. Morgan India Pvt Ltd Total: 0
242 RUNNING FOR: Rajasthan Marudhara Gramin Bank Total: 2
243 RUNNING FOR: Mehta Tubes Ltd Total: 2
244 RUNNING FOR: Liugong India Pvt Ltd Total: 6
245 RUNNING FOR: Deepa Jewellers Ltd Total: 4
246 RUNNING FOR: Arunnachala Impex Pvt Ltd Total: 0
247 RUNNING FOR: Manubhai Gems Pvt Ltd Total: 2
248 RUNNING FOR: Ail Dixon Technologies Pvt Ltd Total: 0
249 RUNNING FOR: Adyar Ananda Bhavan Sweets India Pvt Ltd Total: 1
250 RUNNING FOR: Avana Logistek Ltd Total: 0
251 RUNNING FOR: Anjaney Ferro Alloys Ltd Total: 1
252 RUNNING FOR: Meril Healthcare Pvt Ltd Total: 0
253 RUNNING FOR: Adani Bunkering Pvt Ltd Total: 0
254 RUNNING FOR: Novo Nordisk Service Centre (India) Pvt Ltd Total: 0
255 RUNNING FOR: Adient India Pvt Ltd Total: 0
256 RUNNING FOR: Wpp Media India Pvt Ltd Total: 0
257 RUNNING FOR: K.P.Manish Global Ingredients Pvt Ltd Total: 1
258 RUNNING FOR: Pratishtha Commercial Pvt Ltd Total: 1
259 RUNNING FOR: Hero Cycles Ltd Total: 6
260 RUNNING FOR: Jay Chemical Industries Pvt Ltd Total: 1
261 RUNNING FOR: Satyam Auto Components Pvt Ltd Total: 2
262 RUNNING FOR: Gvk Power (Goindwal Sahib) Ltd Total: 0
263 RUNNING FOR: Shubham Chemicals And Solvents Ltd Total: 4
264 RUNNING FOR: Falcon Marine Exports Ltd Total: 4
265 RUNNING FOR: Tamilnadu State Transport Corporation (Madurai) Ltd Total: 1
266 RUNNING FOR: Roadway Solutions India Infra Ltd Total: 0
267 RUNNING FOR: Trichur Sundaram Santhanam And Family Pvt Ltd Total: 0
268 RUNNING FOR: Velocis Systems Pvt Ltd Total: 1
269 RUNNING FOR: Navrathan Jewellers Pvt Ltd Total: 1
270 RUNNING FOR: Jc Jewellers (Chennai) Pvt Ltd Total: 0
271 RUNNING FOR: Kun Motor Co Pvt Ltd Total: 0
272 RUNNING FOR: Bright Metals (India) Pvt Ltd Total: 1
273 RUNNING FOR: Bharat Fritz Werner Ltd Total: 0
274 RUNNING FOR: Honeywell International (India) Pvt Ltd Total: 13
275 RUNNING FOR: Arliga Ecoworld Infrastructure Pvt Ltd Total: 0
276 RUNNING FOR: Ramalingam Construction Company Pvt Ltd Total: 0
277 RUNNING FOR: Gammon Engineers And Contractors Pvt Ltd Total: 1
278 RUNNING FOR: K.N.Resources Pvt Ltd Total: 0
279 RUNNING FOR: Bhartiya Urban Pvt Ltd Total: 1
280 RUNNING FOR: Sri Siddharth Infratech & Services (I) Pvt Ltd Total: 1
281 RUNNING FOR: Calderys India Refractories Ltd Total: 1
282 RUNNING FOR: Sandhya Aqua Exports Pvt Ltd Total: 0
283 RUNNING FOR: Lanson Motors Pvt Ltd Total: 1
284 RUNNING FOR: Sks Ispat And Power Ltd Total: 2
285 RUNNING FOR: Mangal Industries Ltd Total: 6
286 RUNNING FOR: Sponge Sales India Pvt Ltd Total: 0
287 RUNNING FOR: Becton Dickinson India Pvt Ltd. Total: 16
288 RUNNING FOR: Vpk Motors Pvt Ltd Total: 0
289 RUNNING FOR: Amdd Foods Pvt Ltd Total: 0
290 RUNNING FOR: Suraj Impex (India) Pvt Ltd Total: 1
291 RUNNING FOR: Ushodaya Enterprises Pvt Ltd Total: 9
292 RUNNING FOR: New Saravana Stores Bramandamai Pvt Ltd Total: 0
293 RUNNING FOR: Hathway Digital Ltd Total: 1
294 RUNNING FOR: L And W Construction Pvt Ltd Total: 40
295 RUNNING FOR: Krishna Sheet Processors Pvt Ltd Total: 1
296 RUNNING FOR: K Drive Mobility Solutions Pvt Ltd Total: 0
297 RUNNING FOR: Delhi Tourism And Transportation Development Corporation Ltd Total: 2
298 RUNNING FOR: Rajasthan Liquors Ltd Total: 2
299 RUNNING FOR: Vivriti Capital Ltd Total: 0
300 RUNNING FOR: Tata Toyo Radiator Ltd Total: 1
301 RUNNING FOR: Gadre Marine Export Pvt Ltd Total: 6
302 RUNNING FOR: Sun Direct Tv Pvt Ltd Total: 4
303 RUNNING FOR: Cinepolis India Pvt Ltd Total: 2
304 RUNNING FOR: Par Formulations Pvt Ltd Total: 1
305 RUNNING FOR: Kalika Steel Alloys Pvt Ltd Total: 1
306 RUNNING FOR: Nike India Pvt Ltd Total: 1
307 RUNNING FOR: Narbheram Power And Steel Pvt Ltd Total: 1
308 RUNNING FOR: Clarion India Pvt Ltd Total: 3
309 RUNNING FOR: Trn Energy Pvt Ltd Total: 0
310 RUNNING FOR: Gold Plus Float Glass Pvt Ltd Total: 0
311 RUNNING FOR: Paymate India Ltd Total: 0
312 RUNNING FOR: Wipro Pari Pvt Ltd Total: 0
313 RUNNING FOR: Osc Steel Pvt Ltd Total: 1
314 RUNNING FOR: Tm International Logistics Ltd Total: 8
315 RUNNING FOR: Adm Agro Industries Kota & Akola Pvt Ltd Total: 0
316 RUNNING FOR: Volvo Auto India Pvt Ltd Total: 2
317 RUNNING FOR: Eveready Spinning Mills Pvt Ltd Total: 0
318 RUNNING FOR: Harman Finochem Ltd Total: 1
319 RUNNING FOR: Parakh Agro Industries Ltd Total: 5
320 RUNNING FOR: Prakash Ferrous Industries Pvt Ltd Total: 1
321 RUNNING FOR: Marsh India Insurance Brokers Pvt Ltd. Total: 2
322 RUNNING FOR: Sanyo Special Steel Manufacturing India Pvt Ltd Total: 0
323 RUNNING FOR: Globe Capital Market Ltd Total: 10
324 RUNNING FOR: Integrated Service Point Ltd Total: 1
325 RUNNING FOR: Teva Api India Pvt Ltd Total: 0
326 RUNNING FOR: Sunfresh Agro Industries Pvt Ltd Total: 1
327 RUNNING FOR: Impact Therapeutics Ltd Total: 0
328 RUNNING FOR: S.T. Cottex Exports Pvt Ltd Total: 1
329 RUNNING FOR: Wave Industries Pvt Ltd Total: 0
330 RUNNING FOR: Aml Motors Pvt Ltd Total: 0
331 RUNNING FOR: Omsairam Steels And Alloys Pvt Ltd Total: 1
332 RUNNING FOR: Prestige Feed Mills Ltd Total: 0
333 RUNNING FOR: Laborate Pharmaceuticals India Ltd Total: 10
334 RUNNING FOR: Raunaq Steels Trading Pvt Ltd Total: 2
335 RUNNING FOR: Microland Ltd Total: 0
336 RUNNING FOR: Times Internet Ltd Total: 7
337 RUNNING FOR: Ab Jewels Pvt Ltd Total: 4
338 RUNNING FOR: Finestar Jewellery & Diamonds Pvt Ltd Total: 1
339 RUNNING FOR: Assam Power Generation Corporation Ltd Total: 1
340 RUNNING FOR: Sahrudaya Health Care Pvt Ltd Total: 0
341 RUNNING FOR: Arcesium India Pvt Ltd Total: 0
342 RUNNING FOR: Venco Research And Breeding Farm Pvt Ltd Total: 0
343 RUNNING FOR: Bikanervala Foods Pvt Ltd Total: 1
344 RUNNING FOR: Hindustan Pencils Pvt Ltd Total: 8
345 RUNNING FOR: Ebro India Pvt Ltd Total: 1
346 RUNNING FOR: Sparsh Industries Pvt Ltd Total: 2
347 RUNNING FOR: Encube Ethicals Pvt Ltd Total: 3
348 RUNNING FOR: Bright Lifecare Pvt Ltd Total: 3
349 RUNNING FOR: Santhoshimathaa Oils And Fats Pvt Ltd Total: 0
350 RUNNING FOR: Adani Logistics Ltd Total: 5
351 RUNNING FOR: Popular Mega Motors India Pvt Ltd Total: 0
352 RUNNING FOR: Bdg Metal And Power Ltd Total: 1
353 RUNNING FOR: Mercer Consulting (India) Pvt Ltd Total: 0
354 RUNNING FOR: John Distilleries Pvt Ltd Total: 2
355 RUNNING FOR: K H Exports India Pvt Ltd Total: 0
356 RUNNING FOR: Indian Additives Ltd Total: 3
357 RUNNING FOR: Badve Autocomps Pvt Ltd Total: 0
358 RUNNING FOR: Aarti Steel International Ltd Total: 0
359 RUNNING FOR: Tamilnadu State Transport Corporation Salem Ltd Total: 2
360 RUNNING FOR: Smfg India Home Finance Company Ltd Total: 0
361 RUNNING FOR: Fortune Metaliks Ltd Total: 1
362 RUNNING FOR: Apollo Multispeciality Hospitals Ltd Total: 0
363 RUNNING FOR: Unilever India Exports Ltd Total: 1
364 RUNNING FOR: Tcs E-Serve International Ltd Total: 1
365 RUNNING FOR: Reaghan Fashions Pvt Ltd Total: 1
366 RUNNING FOR: Sri Balaha Chemicals Pvt Ltd Total: 2
367 RUNNING FOR: Thomson Reuters International Services Pvt Ltd Total: 0
368 RUNNING FOR: Mccain Foods India Pvt Ltd Total: 7
369 RUNNING FOR: Quanteco World Ltd Total: 0
370 RUNNING FOR: Khosla Electronics Pvt Ltd Total: 1

In [4]:
from datetime import datetime
csv_name = f"gst_results_{datetime.now().strftime("%H%M%S")}.csv"

df = pd.DataFrame(results)
df.to_csv(csv_name, index=False)
print(f"[SAVED] {csv_name}")

[SAVED] gst_results_103904.csv